site_name: Perk Examples Kit
site_description: Documentation for the Perk Examples Kit on Community Content
docs_dir: docs
extra_css:
  - styles/extra.css
theme:
  palette:
    scheme: slate
    primary: blue
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - toc.integrate
    - navigation.expand
  font:
      text: Lato
      code: JetBrains Mono
  
nav:
  - Documentation:
    - index.md
    - creating-perks.md
    - Donate:
      - donate/about.md
      - donate/create-perk.md
      - donate/settings.md
    - Speed Boost:
      - speed-boost/about.md
      - speed-boost/create-perk.md
      - speed-boost/settings.md
    - Resource Shop:
      - resource-shop/about.md
      - resource-shop/settings.md
      - resource-shop/shop-data.md
    - Title Shop:
      - title-shop/about.md
      - title-shop/settings.md
      - title-shop/shop-data.md
    - VIP Shop:
      - vip-shop/about.md
      - vip-shop/settings.md
      - vip-shop/create-perk.md

  - Core Games:
    - https://coregames.com
  - Twitter:
    - https://twitter.com/PIXELDEPTH

  - GitHub:
    - https://pixeldepth.net

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - markdown.extensions.codehilite:
      guess_lang: false
